server:
  port: 8080

spring:
  redis:
    host: 192.168.0.113  #redis主机ip地址
    password: wxfyyzy115
    port: 6379
    jedis:
      pool:
        max-active: 10 #最大连接数
        max-idle: 6 #最大空闲数
        min-idle: 2 #最小空闲数
    timeout: 2000 #连接超时